language: python
group: travis_lts
sudo: false

services:
  - docker

before_install:
  # - export RIAK_ADMIN="riak-admin"
  - export DOCKER_HOST=tcp://0.0.0.0:2375
  - export DOCKER_CLUSTER=1
  - python setup.py setup_riak

python:
  - '3.5.4'
  - '3.6.4'

install:
  - pip install .
  - pip install coveralls

script:
  - nosetests -v

after_success:
  - coveralls
