language: python
# dist: trusty  # have no preinstalled riak service
sudo: false

services:
  - docker

before_install:
  # - export RIAK_ADMIN="riak-admin"
  - export DOCKER_HOST=tcp://0.0.0.0:2375
  - export DOCKER_CLUSTER=1
  - python setup.py setup_riak

python:
  - '3.5.0'
  - '3.5.1'
  - '3.5.2'
  - '3.6.0'

install:
  - pip install .
  - pip install coveralls

script:
  - nosetests -v

after_success:
  - coveralls
